{% set version = "0.15.0" %}

package:
  name: joblib
  version: {{ version }}

source:
  url: https://github.com/joblib/joblib/archive/{{ version }}.tar.gz
  sha256: 7a08e3df42e376037df74ca4e2343e24410a9d4abf16fade16cfd20885d91cb8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - joblib

about:
  home: http://packages.python.org/joblib/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Python function as pipeline jobs

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
