{% set version = "0.12.2" %}

package:
  name: joblib
  version: {{ version }}

source:
  fn: joblib-{{ version }}.tar.gz
  url: https://github.com/joblib/joblib/archive/{{ version }}.tar.gz
  sha256: 6d999bdde76c612140eccbfd5cd2e5c1de649a403ae7f8125958dce6936509e6

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - joblib

about:
  home: http://packages.python.org/joblib/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Python function as pipeline jobs.'

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
