{% set version = "1.4.2" %}

package:
  name: joblib
  version: {{ version }}

source:
  url: https://github.com/joblib/joblib/archive/{{ version }}.tar.gz
  sha256: 1d95f5f3ab303be89aa4666956bf05a589f56e52c29b836267c8e3885223ff90

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - joblib
    - joblib.externals

about:
  home: https://pypi.org/project/joblib/
  summary: 'Lightweight pipelining: using Python functions as pipeline jobs.'
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
    - ogrisel
    - lesteve
    - tomMoral
    - pierreglaser
